name: Zeek nightly build

on:
  schedule:
  - cron: 0 0 * * *

jobs:
  test-nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: 0xxon/action-zkg-install@ubuntu-24.04
      with:
        pkg: ${{ github.server_url }}/${{ github.repository }}
        zeek_version: zeek-nightly
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: zkg-logs
        path: ${{ github.workspace }}/.action-zkg-install/artifacts
